### ISSUE TITLE
How to install in Kali linux?

### ISSUE THREAD

**Issue by ts23944** [tharyckgusmao/Skill-Share-Crawler---DL#10]
Hi , I am a Linux beginner .. I dont know how to install the zip files after I downloaded in my laptop.. I need need it urgent becouse my SS account will expired soon.. please let me know how to install it.. Thanks you

**Comment by tharyckgusmao** [comment]
Hello;

Are you all right? hope so.

Sorry for my bad English.

Well the steps for you to use the crawler are:

Install Node.js on your machine:

`https://nodejs.org/en/
`
Install Firefox:

`https://www.mozilla.org/en/firefox/new/
`
Install Geckoo Driver:

`https://github.com/mozilla/geckodriver/releases
`
Authenticate only once in the mobile application.

go to the project folder and run this command to install the libraries used:

`npm install
`
later to fix a bug in one of the libraries:

`npm run patch
`
and run the project:

`npm run start
`
will open a terminal as in the images. If everything is configured correct you will enter your login and password in the app and later the firefox will open automatically you click on authenticate by facebook, wait for the firefox will close and return to the terminal, and you choose what you want to download.

Any specific questions I am at your disposal;

If you liked the project of a little star.
thank you!

**Comment by LIUMUCHEN** [comment]
Now it can not work, only download the first preview video.

**Comment by tharyckgusmao** [comment]
Look. You need an account that has a valid license,or use trial license, and do not forget to log in once in the Android / IOS application for the crawler to work.
thanks.

**Comment by LIUMUCHEN** [comment]
Very surprised to receive your reply, thank you for your work.

More unclear is: need to login in Android system? I‘’m running in windows.

**Comment by tharyckgusmao** [comment]
You need at least once to authenticate on some Iphone or android application to enable some features in your login, so we can use the scan via dirty session. Once you log in, you no longer need the applications.

Any questions I'm here.
Sorry for my English.
If you like the app do not forget to leave a little star in the project, thank you.

**Comment by LIUMUCHEN** [comment]
Thank you for your reply, can you still support other browsers? Such as chrome.
best regards.

**Comment by tharyckgusmao** [comment]
Do not. the gecko driver only for firefox.
You need the browser just to authenticate due to the google captcha antibotte, later I will implement it without the browser, use authentication by facebook to normal not be working.

**Comment by LIUMUCHEN** [comment]
Thanks and hope constantly updated.
(Only available in public version)

**Comment by tharyckgusmao** [comment]
Whenever possible I try to update or fix something, or answer the issues.
But lately, I've been working hard.

Thank you and a great day.

**Comment by ts23944** [comment]
Ok I got it, thank you so much for the reply :)
