### ISSUE TITLE
Opens Firefox welcome page everytime

### ISSUE THREAD

**Issue by Adarsh777** [tharyckgusmao/Skill-Share-Crawler---DL#12]
Hi,
Whenever i try to start script it opens a firefox welcome page. How to fix it ?
Thank You

**Comment by tharyckgusmao** [comment]
Hmm. Do you get any errors, or warning or message on the console?
What version of your firefox?

**Comment by Adarsh777** [comment]
No, I'm using Firefox v57.0.4.

**Comment by tharyckgusmao** [comment]
Hi, can you please test this little trick that I present in this question?

[Issue 8](https://github.com/tharyckgusmao/Skill-Share-Crawler---DL/issues/8)

**Comment by Adarsh777** [comment]
I tried the method issue 8 but it not worked.
