### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by Adarsh777** [tharyckgusmao/Skill-Share-Crawler---DL#13]
Hi,
I'm getting login error (incorrect username and password) with captcha everytime. When i try more than 3 to 4 times it gives error you have (Sorry, there have been too many unsuccessful attempts to login to your account. Please try again later.)
How to fix this problem ? Help Needed.
Thank You

**Comment by tharyckgusmao** [comment]
hi, Please use facebook authentication. Google captcha not work more.
