### ISSUE TITLE
 I can only download the first introduction video, others had no speed?

### ISSUE THREAD

**Issue by acapellaa** [tharyckgusmao/Skill-Share-Crawler---DL#14]
![qq 20180125105755](https://user-images.githubusercontent.com/22720309/35368472-7a46ec58-01be-11e8-950a-72470195d15e.png)
Have i missing any setting?
The id is 424465508

**Comment by tharyckgusmao** [comment]
Hello. do not forget to log in only once in the ios / android application to activate the crawler and verify if your account is a premium account or if you are still in trial time. do not hesitate to leave a star on the project. validate these points and give me a fedback. Thx

**Comment by acapellaa** [comment]
YES, becoming premium account can solve the problem.THANKS!
