### ISSUE TITLE
Is it still working as of today?

### ISSUE THREAD

**Issue by joaopedrosantos** [tharyckgusmao/Skill-Share-Crawler---DL#17]
I can't use it, if I add the course link, it fails.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v8.11.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle skillshare_dl@1.0.0~prestart: skillshare_dl@1.0.0
6 info lifecycle skillshare_dl@1.0.0~start: skillshare_dl@1.0.0
7 verbose lifecycle skillshare_dl@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle skillshare_dl@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\SkillShare\node_modules\.bin;C:\Users\joxo\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Program Files\nodejs\;C:\Users\joxoo\AppData\Local\Microsoft\WindowsApps;C:\Users\joxoo\AppData\Roaming\npm
9 verbose lifecycle skillshare_dl@1.0.0~start: CWD: C:\SkillShare
10 silly lifecycle skillshare_dl@1.0.0~start: Args: [ '/d /s /c', 'node index.js' ]
11 silly lifecycle skillshare_dl@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle skillshare_dl@1.0.0~start: Failed to exec start script
13 verbose stack Error: skillshare_dl@1.0.0 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid skillshare_dl@1.0.0
15 verbose cwd C:\SkillShare
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
18 verbose node v8.11.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error skillshare_dl@1.0.0 start: `node index.js`
22 error Exit status 1
23 error Failed at the skillshare_dl@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by tharyckgusmao** [comment]
Yes, it's still working.

Do you have a trial account, do you need an active account or a trial?
You should add the course id as explained in the readme not the link.
Did you configure the firefox driver?
Do not forget to log in only once for the mobile android / ios app to activate the crawler.


Please check this information and let me know.
Thank you, do not forget to leave a little star when everything works.
