### ISSUE TITLE
Can't Download

### ISSUE THREAD

**Issue by ZephyrASZ** [tharyckgusmao/Skill-Share-Crawler---DL#20]
I can't seem to download things. Whenever the "Enter ID video Skill Share:" prompt pops up, it's immediately replaced/taken over by "PS C:\Skillshare-DL>"

![screenshot 3](https://user-images.githubusercontent.com/40257931/41501038-4441cdb8-71cf-11e8-84e9-8074dda45224.png)

**Comment by noxtare** [comment]
![image](https://user-images.githubusercontent.com/7343904/42275933-782773f0-7fc4-11e8-8812-14d9ec137308.png)
 same it wont download :(

**Comment by noxtare** [comment]
i think we are just using the tool wrong xD
OP please help us :P

**Comment by avnlevent** [comment]
I can download them well.
But I'm not run from powershell, I run on Node CMD (when you install node, there is an icon of Node command, or you can make a shortcut with below string).
C:\Windows\System32\cmd.exe /k "C:\Program Files\nodejs\nodevars.bat"

![image](https://user-images.githubusercontent.com/20356159/42551192-440a2ae0-8500-11e8-9d75-5d015d364079.png)

**Comment by milanavanti** [comment]
As "noxtare" mentioned above in image, I'm having the same issue, whenever i select any one of the 3 options before download, it is taking me outside. I did everything with step by step as mentioned in readme. Please help.

Thanks in Advance
Milan Gautam

**Comment by tharyckgusmao** [comment]
Hello guys.

Please follow these steps:

1 - Install the gecko driver and test it, remember to put environment variables, test in cmd: geckodriver.
2 - Do not use the power shell, I only tested with the traditional cmd and I made about 30 gb of download without interruption.
3 - Have firefox installed on the machine.
4 - Run the cmd in administrator mode, enter the project folder by cmd `"cd folder"`, install the packages with` "npm install & npm run patch" `or separate, run the project with `"npm run start".`

Follow these steps, there is no error, remember the environment variables for geckodriver and node. This noxtare error is probably something with the powershell I have not tested on it.
