### ISSUE TITLE
Ability to download specific videos of the course

### ISSUE THREAD

**Issue by shantanub08** [tharyckgusmao/Skill-Share-Crawler---DL#21]
I'm new to GitHub so I'm not quite sure which section to post this (I mean I don't want to make this look like an Issue but rather a feature to be implemented in the future so we can manually resume/re-download failed videos by their Video #)

**Comment by tharyckgusmao** [comment]
Hello Friend.
Currently I am not having time to play with the project, but an interesting suggestion, if you are a developer you can make the changes and upload to the project that I commit and give the credits.

Do not forget to leave a little star if you liked the project.
Thank you

**Comment by sellmeformoney** [comment]
You just need to open Chrome Devtool, click on Network tab, then play the video you want to download. In Network tab, right click name of video, open in new tab and download it
![Screenshot (432)_LI](https://user-images.githubusercontent.com/46379595/55851467-e5282400-5b82-11e9-94fd-2e16bf9926b2.jpg)
