### ISSUE TITLE
I get this error i guess it is related to geckodriver but i was unable to solve it!! please any suggestions?

### ISSUE THREAD

**Issue by nabilazri** [tharyckgusmao/Skill-Share-Crawler---DL#22]
.D:\skillshare\Skill-Share-Crawler---DL-master\node_modules\selenium-webdriver\lib\promise.js:2634
        throw error;
        ^

WebDriverError
    at Object.throwDecodedError (D:\skillshare\Skill-Share-Crawler---DL-master\node_modules\selenium-webdriver\lib\error.js:489:11)
    at parseHttpResponse (D:\skillshare\Skill-Share-Crawler---DL-master\node_modules\selenium-webdriver\lib\http.js:519:13)
    at doSend.then.response (D:\skillshare\Skill-Share-Crawler---DL-master\node_modules\selenium-webdriver\lib\http.js:441:30)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
From: Task: WebDriver.navigate().to(https://www.skillshare.com/?via=header)
    at thenableWebDriverProxy.schedule (D:\skillshare\Skill-Share-Crawler---DL-master\node_modules\selenium-webdriver\lib\webdriver.js:816:17)
    at Navigation.to (D:\skillshare\Skill-Share-Crawler---DL-master\node_modules\selenium-webdriver\lib\webdriver.js:1140:25)
    at thenableWebDriverProxy.get (D:\skillshare\Skill-Share-Crawler---DL-master\node_modules\selenium-webdriver\lib\webdriver.js:997:28)
    at Login.getLoginCredentials (D:\skillshare\Skill-Share-Crawler---DL-master\app\components\Auth.js:93:12)
    at inquirer.prompt.then (D:\skillshare\Skill-Share-Crawler---DL-master\app\components\Auth.js:52:53)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! skillshare_dl@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the skillshare_dl@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\{user}\AppData\Roaming\npm-cache\_logs\2018-09-03T11_17_24_404Z-debug.log

**Comment by designer91** [comment]
Hey,
I tried this but nothing changed, I got the same old error
when I put my credentials, it starts launching Firefox, but it gives me a security issue like is shown in the image below:
[https://s19.postimg.cc/8lpee291v/2018-09-04_11-38-28.jpg](url)

**Comment by designer91** [comment]
I fixed the problem of the certificate and logged in with Facebook, same problem!!
If you succeed downloading, please provide me with the information about the Firefox version, the gecko driver version and the node version. 
Regards!

**Comment by tharyckgusmao** [comment]
geckodriver 0.16.1 
node v7.10.0
firefox 53.0.3 (64-bit)
Tested in linux Manjaro and Windows 10.

**Comment by tharyckgusmao** [comment]
Hello my friend.

  Do not be able to identify the error that you are having, but I believe it is between the webdriver and firefox.

  To connote this situation I updated the tool for manual authentication support.

Follow the tutorial:

Update the tool:

**`git pull or download manually
`**

Run the tool:

**`npm run start
`**

Choose option 2:

![image](https://user-images.githubusercontent.com/11817448/45116060-11c91880-b128-11e8-91c9-257184860cfd.png)

![image](https://user-images.githubusercontent.com/11817448/45116153-4d63e280-b128-11e8-919d-1cada0b6c490.png)

Open your browser manually, log on to the skillshare, open the console ctrl + i or f12 and run this command in the console:

**`document.cookie
`**

![image](https://user-images.githubusercontent.com/11817448/45116212-653b6680-b128-11e8-9c17-7d10cfe2fb5d.png)

Copy the return and paste text into the tool:
![image](https://user-images.githubusercontent.com/11817448/45116238-76847300-b128-11e8-86c8-61a9f81220c1.png)

Press enter and proceed with downloads
![image](https://user-images.githubusercontent.com/11817448/45116291-a764a800-b128-11e8-8291-f45a7d2033b7.png)


See you.

**Comment by designer91** [comment]
Hey, I tried this and it works like a charm, thank you ;)

**Comment by ffalpha** [comment]
After Selecting the option 2 nothing happens .Any Idea?
![13](https://user-images.githubusercontent.com/31257148/63497022-9dc28480-c4e0-11e9-95e8-ca30f83ae8a4.PNG)

**Comment by mark593** [comment]
![Capture](https://user-images.githubusercontent.com/60008451/72624217-74e2d600-393e-11ea-86a3-54a7d3157600.PNG)

I'm using opera browser and in between the download of course I'm getting this error 
**_Can You help me to fix this ASAP?_**

**Comment by Jigs1612** [comment]
hello, In my case it did not move forward after manual auth.
What can I do?

![Capturbe](https://user-images.githubusercontent.com/55726835/78772998-37776d00-79b0-11ea-8e39-9529bd8fff36.PNG)

**Comment by Fantastic-Dave** [comment]
if you have git installed open a git bash in the skillshare-downloader folder and then try running it. that worked for me

**Comment by highrup** [comment]
> .D:\skillshare\Skill-Share-Crawler---DL-master\node_modules\selenium-webdriver\lib\promise.js:2634
> throw error;
> ^
> 
> WebDriverError
> at Object.throwDecodedError (D:\skillshare\Skill-Share-Crawler---DL-master\node_modules\selenium-webdriver\lib\error.js:489:11)
> at parseHttpResponse (D:\skillshare\Skill-Share-Crawler---DL-master\node_modules\selenium-webdriver\lib\http.js:519:13)
> at doSend.then.response (D:\skillshare\Skill-Share-Crawler---DL-master\node_modules\selenium-webdriver\lib\http.js:441:30)
> at
> at process._tickDomainCallback (internal/process/next_tick.js:228:7)
> From: Task: WebDriver.navigate().to(https://www.skillshare.com/?via=header)
> at thenableWebDriverProxy.schedule (D:\skillshare\Skill-Share-Crawler---DL-master\node_modules\selenium-webdriver\lib\webdriver.js:816:17)
> at Navigation.to (D:\skillshare\Skill-Share-Crawler---DL-master\node_modules\selenium-webdriver\lib\webdriver.js:1140:25)
> at thenableWebDriverProxy.get (D:\skillshare\Skill-Share-Crawler---DL-master\node_modules\selenium-webdriver\lib\webdriver.js:997:28)
> at Login.getLoginCredentials (D:\skillshare\Skill-Share-Crawler---DL-master\app\components\Auth.js:93:12)
> at inquirer.prompt.then (D:\skillshare\Skill-Share-Crawler---DL-master\app\components\Auth.js:52:53)
> at
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! skillshare_dl@1.0.0 start: `node index.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the skillshare_dl@1.0.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users{user}\AppData\Roaming\npm-cache_logs\2018-09-03T11_17_24_404Z-debug.log

is this program no longer working? im encountering this same error now and i had been using this a year or so ago
