### ISSUE TITLE
Program exits as soon as I select auth method

### ISSUE THREAD

**Issue by CaptainJawZ** [tharyckgusmao/Skill-Share-Crawler---DL#24]
Sorry if this is a noob problem! I followed the instructions and it's all well until the login part.
I run npm run start, and then it loads the program
Now, no matter what auth method I chose either automatic or manual, the program exits before I can input an answer:
I'm using CMD, this is for example what happens right after I select automatically auth:

? What do you want to do ? 1 - Automatically Auth
? Enter your Skill Share e-mail address:

E:\OneDrive\Programs\Skill-Share-Crawler---DL-master>

It doesn't give me the option to write down my email address, or the cookie

I would appreciate any help!

**Comment by tharyckgusmao** [comment]
Hello my friend, if you do not configure the gecko driver, I recommend that you use an auth manual second option. 
#22 
Do you have the same problem with an auth manual?
Can you run cmd as an administrator?

**Comment by CaptainJawZ** [comment]
Hello! thank you so much for your quick reply!
I have the same problem with auth manual, and also if I run it as administrator.

**Comment by tharyckgusmao** [comment]
Very strange no error reported in console. Can some people run through the powershell you tested?
Can you inform me the version of the node you are using?

**Comment by CaptainJawZ** [comment]
Sorry for the late response! I just tried running it through powershell and got the same results.

As for Node, I am using 10.7.0

**Comment by CaptainJawZ** [comment]
It seems like it was it! I uninstalled Node, and installed 8.11.4 LTS and it seems to be working now! thank you so much!
