### ISSUE TITLE
It says,"npm is not a command"!

### ISSUE THREAD

**Issue by tejas9547** [tharyckgusmao/Skill-Share-Crawler---DL#33]
I've done all the things till the one where I have to type in the command,"npm install" and after I click ENTER; the resultant screen says that, " npm is not recognized as an internal or external command,
operable program or batch file."!
![screenshot 00](https://user-images.githubusercontent.com/48293651/53903431-b55c9c80-4069-11e9-9b99-956db7c10a3a.png)

**Comment by tharyckgusmao** [comment]
Hey, first install node and npm, in your windows.
Follow this tutorial https://www.youtube.com/watch?v=eX4V2Hn89ZM&t=89s
