### ISSUE TITLE
Some courses stop downloading unexpectedly on Windows

### ISSUE THREAD

**Issue by ipkpjersi** [tharyckgusmao/Skill-Share-Crawler---DL#4]
Hello,

I love this program  but I do have an issue with it. I think that you should check for invalid characters on Windows (for example, : and " and ?) and then rename them to something else, or simply remove them from the output file altogether. When there is a course that has a file with an invalid name, the entire program crashes and the course cannot be downloaded at all.

Thank you.

**Comment by tharyckgusmao** [comment]
Hello Friend.
I solved this escape caracther problem by replacing the entire replace for my regex replace `(/ [^ a-zA-Z0-9] / g, ""`), can you send me an id that is giving error? so that I can vindicate the error.
Thank you

**Comment by ipkpjersi** [comment]
Oh, I didn't see that you fixed this issue 13 hours ago - it may actually be fixed after all. I will test it and report back.

**Comment by ipkpjersi** [comment]
Sorry for the double post, but I do have an error, not sure if it is related to the naming of files on Windows, though: [!](https://i.imgur.com/QWx0zyk.png)

**Comment by tharyckgusmao** [comment]
This error can come to happen even though I am not treating exceptions for it. What happens and that some positions of the json do not exist can occur from the platform have another standard for this video in question because I download the video in high quality and this feature may not exist for some videos.

Inform me please id so I can evaluate and think about a deal.
Thanks

**Comment by ipkpjersi** [comment]
Hello,

One of the videos that does this is: 57220732

Thanks.

**Comment by tharyckgusmao** [comment]
Did you try to download again and right?
There may have been some interference with a skillshare api.

For me it was 100% top-notch.


![image](https://user-images.githubusercontent.com/11817448/33154469-acd332b0-cfcf-11e7-8b27-97e5e51acf3e.png)

**Comment by ipkpjersi** [comment]
That one worked mostly fine but this one failed a lot: 1654744071

**Comment by tharyckgusmao** [comment]
Everything very strange, I need to separate a day to carry out a thorough debug, for me it did not present any flaw.

![image](https://user-images.githubusercontent.com/11817448/33154854-81630d00-cfd2-11e7-8155-ea77c704e1bd.png)
