### ISSUE TITLE
Ability to change download folder

### ISSUE THREAD

**Issue by Darwish8040** [tharyckgusmao/Skill-Share-Crawler---DL#41]
This crawler works very well but, I have only one issue which is to change the download folder by the user manually. That's my only request. If it's already possible I could appreciate it if someone gave me steps on how to actually do it without breaking the entire thing as I have attempted earlier.

**Comment by tharyckgusmao** [comment]
Dont have option, but you change manually:
change all occurrences word "videos" in file:

[link file](https://github.com/tharyckgusmao/Skill-Share-Crawler---DL/blob/master/app/components/DlPerId.js)

for other word.

or change directly path example:

line 67
fs.writeFileSync(`./videos/..') 

from

fs.writeFileSync('C:/crawvideos/..')

**Comment by tharyckgusmao** [comment]
I don't use it anymore, so I'm not keeping tracker.
