### ISSUE TITLE
How do i install geckodriver on win OS

### ISSUE THREAD

**Issue by sesan** [tharyckgusmao/Skill-Share-Crawler---DL#7]
`(node:14504) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: The geckodriver.exe executable could not be found on the current PATH. Please download the latest version from https://github.com/mozilla/geckodriver/releases/ and ensure it can be found on your PATH.
(node:14504) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

 **Please wait, launching Browser, please resolve the captcha and click sign-ip for continue and wait... **

What am I missing out?

**Comment by Purus** [comment]
How was this issue solved? I have the geckodriver.exe in my PATH.

**Comment by tharyckgusmao** [comment]
Please open a new edition for others who have the same question. Thank you

**Comment by tharyckgusmao** [comment]
If you are using windows maybe this problem can help you


https://github.com/tharyckgusmao/Skill-Share-Crawler---DL/issues/8

2017-12-26 15:41 GMT-02:00 Tharyck Gusmao <thaka.gus@gmail.com>:

>
> Please open a new edition for others who have the same question. Thank you
>
