### ISSUE TITLE
Not Downloading 

### ISSUE THREAD

**Issue by sesan** [tharyckgusmao/Skill-Share-Crawler---DL#8]
![skillshare](https://user-images.githubusercontent.com/5590206/34041859-4f1c8662-e19a-11e7-9064-60ee12e82d04.JPG)
# What Should I do#

**Comment by tharyckgusmao** [comment]
@sesan hello sorry for the delay I've been working a lot these days.


you followed the necessary steps like authenticating in the ios / android app once and installing the geecko driver.

this presented and about the gecko driver is not set in the path.system of the operating system so the node can not realize the flame for it.

In case you are having difficulties to install gecko and configure, you can perform this hack below that will also work.

follows the changes:

run the geckodriver manually:
 find the geckodriver folder on your machine and run through the terminal:

  `   geckodriver`

Open this crawler file;

`App / components / auth.js`

and edit this configuration of the geckodriver that you executed it usually listens on the 4444 switch through your.

look for this block of code in line 86.
```

    let driver = new webdriver.Builder ()
    .forBrowser ('firefox')
    .setFirefoxOptions (options)
    .build ();
```

and edit this line based on your gecko configuration:

    .usingServer ('http://127.0.0.1:4444')


thus:

```
    let driver = new webdriver.Builder ()
    .forBrowser ('firefox')
    .usingServer ('http://127.0.0.1:4444')
    .setFirefoxOptions (options)
    .build ();

```

and run the project again should work by the hour is not recommended but it works.

**Comment by sesan** [comment]
Thanks for the response anyway when you talk about **"steps like authenticating in the ios / android app once and installing the geecko driver."** are you saying I have to download skillshare app to my  ios first and then install geecko on my PC ?

**Comment by tharyckgusmao** [comment]
You must install the application on your smartphone and authenticate at least once a download is available for download.

The gecko driver and an interface to access firefox resources is the only function of it.

are different things but both obligatory steps.

And also firefox installed on your machine.

**Comment by sesan** [comment]
![capture](https://user-images.githubusercontent.com/5590206/34085385-37c26e4e-e390-11e7-97d4-69d1810d7b33.JPG)
**After I login using the npm terminal then firefox comes up then i login into my account and nothing happens after wards**
![image](https://user-images.githubusercontent.com/5590206/34085400-8d562f1c-e390-11e7-88d0-02050048867e.png)

**Comment by tharyckgusmao** [comment]
It waits for the browser to open automatically, and authenticate using the facebook button,
Currently Google is blocking default authentication because of capatcha.

**Comment by sesan** [comment]
THANK YOU !!!!!!!!!!!!!!!!!!! it worked

**Comment by sesan** [comment]
what i simply did was that i added the .usingServer ('http://127.0.0.1:4444') and tried to re-run it and it worked

**Comment by tharyckgusmao** [comment]
I'm glad, any doubt can call that I answer you. Do not forget to give that little star to strengthen the project.
thank you

**Comment by silverbret1709** [comment]
I get the same problem, 1 or 2 option , it stop working

**Comment by med-look** [comment]
> PLEASE HELP!!!
> I did all steps as mentioned above and still stuck at auth. I tried running both options auto auth and manual. it doesn't let me sign in :(
> 
> PS C:\Users\Hashim Malik\Downloads\Skill-Share-Crawler---DL-master> npm run start
> 
> > skillshare_dl@1.0.0 start C:\Users\Hashim Malik\Downloads\Skill-Share-Crawler---DL-master
> > node index.js
> 
> (node:16048) [DEP0006] DeprecationWarning: child_process: options.customFds option is deprecated. Use options.stdio instead.
> 
> / ___| | | __ (_) | | | | / _**| | |** __ _ _ __ ___ | _ \ | | ___ \ | |/ / | | | | | | ___ \ | '_ \ / _` | | '__| / _ \ | | | | | | _**) | | < | | | | | | ___) | | | | | | (_| | | | | __/ | |_| | | |_** |____/ |_|_\ |_| |_| |_| |____/ |_| |_| __,_| |_| ___| |____/ |_____|
> ? What do you want to do ? 2 - Manual Auth
> 
> ![image](https://user-images.githubusercontent.com/45741408/51497243-eba4cc00-1ddb-11e9-975f-c873bffe1210.png)
> 
> ![image](https://user-images.githubusercontent.com/45741408/51497256-f8c1bb00-1ddb-11e9-9cc6-45f4064129bd.png)

anyone ?
